### ISSUE TITLE
Cannot install module

### ISSUE THREAD

**Issue by adoyle-h** [zappjs/zappjs#16]
![image](https://cloud.githubusercontent.com/assets/1998490/10415267/fc7848da-7024-11e5-9563-5ca0d2b6745b.png)

"Module does not exist in the Crystal Hub." often happens. Is it my network problem?

Version:
node v0.12.2
npm 2.13.3
autocode-cli@0.21.1

**Comment by ctate** [comment]
Closing per https://github.com/zappjs/zappjs/issues/17
