### ISSUE TITLE
Cannot search a module

### ISSUE THREAD

**Issue by adoyle-h** [zappjs/zappjs#17]
``` bash
> autocode search crystal/readme                                                                                                                            
Searching for generators matching name (crystal/readme)...
undefined is not a function
```

Version:
node v0.12.2
npm 2.13.3
autocode-cli@0.21.1

**Comment by adoyle-h** [comment]
I think the server of `https://api.crystal.sh` is down.

**Comment by ctate** [comment]
Hi @adoyle-h - the Crystal registry no longer exists and the project is now ZappJS. Instead you can use npm and other registries. Thank you!
