### ISSUE TITLE
Feature Request: Create a private module and install a module from custom url

### ISSUE THREAD

**Issue by adoyle-h** [zappjs/zappjs#18]
I want to create a module for building a part of my own projects. So I want putting this module in other places rather than publishing it to the Crystal Hub. And I can install it from a custom url.

**Comment by ctate** [comment]
Excellent timing - we do plan to release private modules for our innovator accounts. Will send you an email this week to give you early access.

**Comment by ctate** [comment]
Hi @adoyle-h - this project has been renamed to ZappJS and now supports private extensions via npm and other repositories. Please check out the latest and let me know if you have any feedback. Thank you.
