### ISSUE TITLE
Auto-update autocode formula for `brew` (OS X)

### ISSUE THREAD

**Issue by Zearin** [zappjs/zappjs#23]
I just ran the following:

```
$ brew info autocode
autocode: stable 0.20.3 (bottled)
Code automation for every language, library and framework
https://crystal.sh/autocode
Not installed
From: https://github.com/Homebrew/homebrew/blob/master/Library/Formula/autocode.rb
==> Dependencies
Required: node ✔

$ npm -g info autocode@latest version
1.0.3
```

Could you configure autocode so that when there’s a new release, the Homebrew repo gets a Pull Request with the updated formula?

**Comment by ctate** [comment]
Project has been renamed to ZappJS, and don't currently have plans to reintroduce to Homebrew atm. Thank you.
