### ISSUE TITLE
Support for Gulp

### ISSUE THREAD

**Issue by Zearin** [zappjs/zappjs#31]
Grunt is popular, and I give it much respect.  However, Gulp has always “felt” easier to grok for me, because it functions like shell pipelines.  

(Supposedly, a nice side effect is that it runs significantly faster, too, because Grunt prefers to physical files for each task’s I/O, whereas Gulp is fine with piping stuff around without creating files for the intermediate steps.  This makes sense to me, but I can’t say that I _know_ it’s true because don’t have tons of experience with either of them.  I just know that when I have to work with a build system, Gulp is easier for me to understand and work with.)

---

So, how bout some Gulp support? :D

**Comment by Zearin** [comment]
@ctate ping

**Comment by Zearin** [comment]
ping

**Comment by ctate** [comment]
Hey @Zearin - sorry it (literally) took years to get back to you. Not sure if you'd still be interested in Gulp support or not but would love to get your feedback on this project now - which has been renamed to ZappJS. Thank you.
